openapi: 3.0.3

info:
  version: 0.0.1-SNAPSHOT
  title: Calculator Service OpenApi
  description: Микросервис калькулятор
  contact:
    email: gradskovaleksej@gmail.com

tags:
  - Calculator
paths:
  /calculator/offers:
    post:
      tags:
        - Calculator
      description:  расчёт возможных условий кредита
      operationId: calculateOffers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanStatementRequest'
      responses:
        '200':
          description: Предложения возможных условий по кредиту
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOffer'
  
  /calculator/calc:
    post:
      tags:
        - Calculator
      description: валидация присланных данных + скоринг данных + полный расчет параметров кредита
      operationId: calcCredit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScoringData'
      responses:
        200:
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credit'
    

components:
  schemas:
    LoanStatementRequest:
      required:
        - amount
        - term
        - first_name
        - last_name
        - email
        - birthdate
        - passport_series
        - passport_number
      type: object
      properties:
        amount:
          type: number
          nullable: false
          example: 100000
          minimum: 20000
        term:
          type: integer
          nullable: false
          minimum: 6
          example: 6
        first_name:
          type: string
          nullable: false
          example: "Ivanov"
          minLength: 2
          maxLength: 30
        last_name:
          type: string
          nullable: false
          example: "Ivan"
          minLength: 2
          maxLength: 30
        middle_name:
          type: string
          example: "Ivanovich"
          minLength: 2
          maxLength: 30
        email:
          type: string
          nullable: false
          example: "IvanovII@gmail.com"
          pattern: "^[a-z0-9A-Z_!#$%&'*+/=?`{|}~^.-]+@[a-z0-9A-Z.-]+$"
        birthdate:
          type: string
          format: date
          nullable: false
          example: "1999.01.01"
          x-field-extra-annotation: "@ru.gav.creditbank.calculator.validation.CheckAge"
        passport_series:
          nullable: false
          type: string
          maxLength: 4
          minLength: 4
          example: "1111"
        passport_number:
          type: string
          nullable: false
          minLength: 6
          maxLength: 6
          example: "111111"

    LoanOffer:
      type: object
      description: "Предложение по кредиту"
      properties:
        statement_id:
          type: string
          format: uuid
          nullable: false
        requested_amount:
          type: number
          nullable: false
          example: 20000
        total_amount:
          type: number
          nullable: false
          example: 20000
        term:
          type: integer
          nullable: false
          example: 6
        monthly_payment:
          type: number
          nullable: false
          example: 10000
        rate:
          type: number
          nullable: false
          example: 10000
        is_insurance_enabled:
          type: boolean
          nullable: false
        is_salary_client:
          type: boolean
          nullable: false

    ScoringData:
      type: object
      properties:
        amount:
          type: number
        term:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        middle_name:
          type: string
        gender:
          $ref: '#/components/schemas/Gender'
        birthdate:
          type: string
          format: date
        passport_series:
          type: string
        passport_number:
          type: string
        passport_issue_date:
          type: string
          format: date
        passport_issue_branch:
          type: string
        marital_status:
          $ref: '#/components/schemas/MaritalStatus'
        dependentAmount:
          type: integer
        employment:
          $ref: '#/components/schemas/Employment'
        account_number:
          type: string
        is_insurance_enabled:
          type: boolean
        is_salary_client:
          type: boolean

    Gender:
      enum:
        - Male
        - Female

    MaritalStatus:
      enum:
        - Single
        - Married

    Credit:
      type: object
      properties:
        amount:
          type: number
        term:
          type: integer
        monthly_payment:
          type: number
        rate:
          type: number
        psk:
          type: number
        is_insurance_enabled:
          type: boolean
        is_salary_client:
          type: boolean
        payment_schedule:
          type: array
          items:
            $ref: '#/components/schemas/PaymentScheduleElement'

    Employment:
      type: object
      properties:
        employment_status:
          $ref: '#/components/schemas/EmploymentStatus'
        employer_INN:
          type: string
        salary:
          type: number
        position:
          $ref: '#/components/schemas/Position'
        work_experience_total:
          type: integer
        work_experience_current:
          type: integer

    PaymentScheduleElement:
      type: object
      properties:
        number:
          type: integer
        date:
          type: string
          format: date
        total_payment:
          type: number
        interest_payment:
          type: number
        debt_payment:
          type: number
        remaining_debt:
          type: number

    EmploymentStatus:
      enum:
        - Employee
        - Self-employed
        - Unemployed
        - Business_owner

    Position:
      enum:
        - Top_manager
        - Middle_manager
        - Lower_level_manager
        - Contractor
