openapi: 3.0.3

info:
  version: 0.0.1-SNAPSHOT
  title: Calculator Service OpenApi
  description: Микросервис калькулятор
  contact:
    email: gradskovaleksej@gmail.com

tags:
  - name: Calculator
    description: "Calculator API"
paths:
  /calculator/offers:
    post:
      tags:
        - Calculator
      description:  расчёт возможных условий кредита
      operationId: calculateOffers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanStatementRequest'
      responses:
        '200':
          description: Предложения возможных условий по кредиту
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOffer'
        400:
          description: Ошибка при скоринге данных
          content:
            application/json:
              schema:
                type: string
                description: "Ошибка при скоринге {} данных"
  
  /calculator/calc:
    post:
      tags:
        - Calculator
      description: валидация присланных данных + скоринг данных + полный расчет параметров кредита
      operationId: calcCredit
      requestBody:
        content:
          application/json:
            schema:

              $ref: '#/components/schemas/ScoringData'
      responses:
        200:
          description: TODO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credit'
        400:
          description: Ошибка при скоринге данных
          content:
            application/json:
              schema:
                type: string
                description: "Ошибка при скоринге {} данных"


components:
  schemas:
    LoanStatementRequest:
      nullable: false
      required:
        - amount
        - term
        - firstName
        - lastName
        - email
        - birthdate
        - passportSeries
        - passportNumber
      type: object
      properties:
        amount:
          type: number
          nullable: false
          example: 100000
          minimum: 20000
        term:
          type: integer
          nullable: false
          minimum: 6
          example: 6
        firstName:
          type: string
          nullable: false
          example: "Ivanov"
          minLength: 2
          maxLength: 30
        lastName:
          type: string
          nullable: false
          example: "Ivan"
          minLength: 2
          maxLength: 30
        middleName:
          type: string
          example: "Ivanovich"
          minLength: 2
          maxLength: 30
        email:
          type: string
          nullable: false
          example: "IvanovII@gmail.com"
          pattern: "^[a-z0-9A-Z_!#$%&'*+/=?`{|}~^.-]+@[a-z0-9A-Z.-]+$"
        birthdate:
          type: string
          format: date
          nullable: false
          example: "1999.01.01"
          x-field-extra-annotation: "@ru.gav.creditbank.calculator.validation.CheckAge"
        passportSeries:
          nullable: false
          type: string
          maxLength: 4
          minLength: 4
          example: "1111"
        passportNumber:
          type: string
          nullable: false
          minLength: 6
          maxLength: 6
          example: "111111"

    LoanOffer:
      type: object
      description: "Предложение по кредиту"
      properties:
        statementId:
          type: string
          format: uuid
          nullable: false
        requestedAmount:
          type: number
          nullable: false
          example: 20000
        totalAmount:
          type: number
          nullable: false
          example: 20000
        term:
          type: integer
          nullable: false
          example: 6
        monthlyPayment:
          type: number
          nullable: false
          example: 10000
        rate:
          type: number
          nullable: false
          example: 10000
        isInsuranceEnabled:
          type: boolean
          nullable: false
        isSalaryClient:
          type: boolean
          nullable: false

    ScoringData:
      nullable: false
      type: object
      description: Оценочные данные
      required:
        - amount
        - term
        - firstName
        - lastName
        - gender
        - birthdate
        - passportSeries
        - passportNumber
        - passportIssueBranch
        - passportIssueDate
        - employment
        - maritalStatus
        - dependentAmount
        - accountNumber
        - isSalaryClient
        - isInsuranceEnabled
      properties:
        amount:
          type: number
          nullable: false
          example: 20000
        term:
          type: integer
          nullable: false
          minimum: 6
          maximum: 36
        firstName:
          type: string
          nullable: false
          example: "Ivan"
        lastName:
          type: string
          nullable: false
          example: "Ivanov"
        middleName:
          type: string
          example: "Ivanovich"
          nullable: false
        gender:
          $ref: '#/components/schemas/Gender'
        birthdate:
          type: string
          format: date
          nullable: false
          x-field-extra-annotation: "@ru.gav.creditbank.calculator.validation.CheckAge"
        passportSeries:
          type: string
          nullable: false
          example: "1111"
          maxLength: 4
          minLength: 4
        passportNumber:
          type: string
          nullable: false
          minLength: 6
          maxLength: 6
          example: "111111"
        passportIssueDate:
          type: string
          format: date
          nullable: false
        passportIssueBranch:
          type: string
          nullable: false
        maritalStatus:
          $ref: '#/components/schemas/MaritalStatus'
        dependentAmount:
          type: integer
          nullable: false
        employment:
          $ref: '#/components/schemas/Employment'
        accountNumber:
          type: string
          nullable: false
        isInsuranceEnabled:
          type: boolean
          nullable: false
        isSalaryClient:
          type: boolean
          nullable: false


    Gender:
      description: Пол заемщика
      enum:
        - Male
        - Female

    MaritalStatus:
      description: Семейное положение
      enum:
        - Single
        - Married

    Credit:
      description: Данные о посчитанном кредите
      type: object
      properties:
        amount:
          type: number
        term:
          type: integer
        monthlyPayment:
          type: number
        rate:
          type: number
        psk:
          type: number
        isInsuranceEnabled:
          type: boolean
        isSalaryClient:
          type: boolean
        paymentSchedule:
          type: array
          items:
            $ref: '#/components/schemas/PaymentScheduleElement'

    Employment:
      description: Данные работника
      type: object
      properties:
        employmentStatus:
          $ref: '#/components/schemas/EmploymentStatus'
        employerINN:
          type: string
        salary:
          type: number
        position:
          $ref: '#/components/schemas/Position'
        workExperienceTotal:
          type: integer
        workExperienceCurrent:
          type: integer

    PaymentScheduleElement:
      description: Элемент графика платежей
      type: object
      properties:
        number:
          type: integer
        date:
          type: string
          format: date
        totalPayment:
          type: number
        interestPayment:
          type: number
        debtPayment:
          type: number
        remainingDebt:
          type: number

    EmploymentStatus:
      description: Рабочий статус
      enum:
        - Employee
        - Self-employed
        - Unemployed
        - Business_owner

    Position:
      description: Позиция работника
      enum:
        - Top_manager
        - Middle_manager
        - Lower_level_manager
        - Contractor
